FROM ghcr.io/cyber-dojo-languages/csharp:3507507
LABEL maintainer=jon@jaggersoft.com

USER sandbox
COPY . .
RUN ./install.sh

# Ensure root user when container boots.
# This reduces the duration of the cyber-dojo.sh file in the ReqnRoll 
# start-point from ~8 seconds to ~2 seconds!
USER root

