FROM ghcr.io/cyber-dojo-languages/csharp:3507507
LABEL maintainer=jon@jaggersoft.com

USER sandbox
COPY . .
RUN ./install.sh

# Ensure root user when container boots.
# This prevents core dumps for max file-size ulimits being
# exceeded which can otherwise happen for large packages.
USER root

